image: node:7.7

cache:
  paths:
  - node_modules/

pages:
  stage: deploy
  script:
  - npm install
  - node node_modules/docpad/bin/docpad generate -o public --env static
  artifacts:
    paths:
    - public
  only:
  - source

variables:
  GIT_SUBMODULE_STRATEGY: recursive
