image: node:7.7

pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - node node_modules/docpad/bin/docpad generate -o public --env static
  artifacts:
    paths:
    - public
  only:
  - source
